# base image
FROM node:12.2.0-alpine as build

# set working directory
RUN mkdir /paymentworks
WORKDIR /paymentworks

# add `/paymentworks/node_modules/.bin` to $PATH
ENV PATH /paymentworks/node_modules/.bin:$PATH

# install and cache app dependencies
# Add React app to working directory
ADD . /paymentworks/
RUN npm install
RUN npm install react-scripts -g

# start app
RUN npm run build

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.17-alpine

COPY --from=build /paymentworks/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]